### ISSUE TITLE
[Question] Octane?

### ISSUE THREAD

**Issue by OwenMelbz** [stayallive/laravel-eloquent-observable#1]
Hey, how does this package effect "performance" if you're using something like Octane which only boots once? Will that not negate the messaging in the readme about registering them on all application startup?

Thanks!

**Comment by stayallive** [comment]
Jep. When using Octane the only benefit is your workers start quicker. But the effect is mostly negated indeed.

**Comment by OwenMelbz** [comment]
Thanks for clarification! We've been looking into ways to improve performance of our app which is how we came across your package, but as we're already using Octane it doesn't look like it will benefit our set up much, thanks!

**Comment by stayallive** [comment]
Ah yeah, got it!

Hope you are measuring what your performance issues are before optimizing. Unsolicited advice maybe but you can look into tools like Sentry, Blackfire and/or Tideways which have been very helpful to me presently and in the past finding my bottlenecks and performance issues.

Anyway, good luck!
